# copy vs view

In [1]:
import numpy as np

In [3]:
var=np.array([1,2,3,4])
co=var.copy()
print(var)
print('copy',co)

[1 2 3 4]
copy [1 2 3 4]


In [4]:
var=np.array([1,2,3,4])
vi=var.copy()
print(var)
print('view',vi)

[1 2 3 4]
view [1 2 3 4]


# Join array

In [9]:
arr=np.array([1,2,3,4])
arr1=np.array([5,43,5,3])

ar=np.concatenate((arr,arr1))
print(ar)


[ 1  2  3  4  5 43  5  3]


# 2d array

In [17]:
pk=np.array([[1,2],[3,4]])
pk2=np.array([[5,43],[5,3]])
print(pk)
print(pk.shape)

arnew=np.concatenate((pk,pk2),axis=1)
print(arnew)



[[1 2]
 [3 4]]
(2, 2)
[[ 1  2  5 43]
 [ 3  4  5  3]]


In [21]:
pk5=np.array([[1,2],[3,4]])
pk6=np.array([[5,43],[5,3]])


arnew1=np.dstack((pk5,pk6))
print(arnew1)


[[[ 1  5]
  [ 2 43]]

 [[ 3  5]
  [ 4  3]]]


# Split array

# 1d array split

In [23]:
car=np.array([1,2,3,4,5])
a9=np.array_split(var,3)
print(a9)

[array([1, 2]), array([3]), array([4])]


# 2d array

In [26]:
pk2=np.array([[5,43],[5,3],[6,5],[9,0]])
a16=np.array_split(pk2,4,axis=1)
print(a16)

[array([[5],
       [5],
       [6],
       [9]]), array([[43],
       [ 3],
       [ 5],
       [ 0]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]
