# Indexing

In [1]:
import numpy as np
var1=np.array([1,2,3,4])
print(var1[-3])

2


In [10]:
var2=np.array([[1,2,3,4],[8,9,5,4]])
print(var2)
print(var2.ndim)
print(var2[0,3])

[[1 2 3 4]
 [8 9 5 4]]
2
4


In [14]:
var3=np.array([[[6,2],[1,8]]])
print(var3)
print(var3[0,0,1])

[[[6 2]
  [1 8]]]
2


# slicing

In [15]:
var1=np.array([1,2,3,4])
print(var1[1:3])

[2 3]


In [17]:
var2=np.array([[1,2,3,4],[8,9,5,4]])
print(var2[0,1:3])

[2 3]
