# Matrix


In [4]:
import numpy as np
var=np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [18]:
var=np.matrix([[1,2,4,3],[1,2,3,4],[1,2,3,4],[2,3,4,5]])
print(var)
var2=np.matrix([[1,2],[1,2],[1,2],[1,2]])
print()
print(var2)
print(var.dot(var2))

[[1 2 4 3]
 [1 2 3 4]
 [1 2 3 4]
 [2 3 4 5]]

[[1 2]
 [1 2]
 [1 2]
 [1 2]]
[[10 20]
 [10 20]
 [10 20]
 [14 28]]


# Matrix Function

In [23]:
mat=np.matrix([[1,2],[3,4],[5,0]])
print(mat)
# print(np.transpose(mat))
print(mat.T)
print(np.swapaxes(mat,0,1))

[[1 2]
 [3 4]
 [5 0]]
[[1 3 5]
 [2 4 0]]
[[1 3 5]
 [2 4 0]]


In [34]:
sq=np.matrix([[1,9],[2,8]])
print(sq)

[[1 9]
 [2 8]]


In [36]:
print(np.swapaxes(sq,0,1))
print()
print(np.linalg.inv(sq) )

[[1 2]
 [9 8]]

[[-0.8  0.9]
 [ 0.2 -0.1]]


# Power

In [40]:
print(np.linalg.matrix_power(sq,2))

[[19 81]
 [18 82]]


In [41]:
print(np.linalg.det(sq))

-9.999999999999998
