# Numpy arrays

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
x=['hi','ram',1,111,3]
c=np.array(x)
print(c.ndim)

1


In [9]:
li=[]
for i in range(1,4):
    q=input("enter numbers")
    li.append(int(q))
arr=np.array(li)
print(arr)

enter numbers4
enter numbers45
enter numbers65
[ 4 45 65]


SyntaxError: invalid syntax (1926259798.py, line 1)

In [18]:
ar2=np.array([[1,2,3,4,5,6],[12,345,45,76,4,5]])
ar2.ndim
print(ar2)

[[  1   2   3   4   5   6]
 [ 12 345  45  76   4   5]]


In [21]:
ar2=np.array([[[1,2,3,4,5,6],[12,345,45,76,4,5],[1,23,5,6,4,3]]])
print(ar2.ndim)
print(ar2)

3
[[[  1   2   3   4   5   6]
  [ 12 345  45  76   4   5]
  [  1  23   5   6   4   3]]]


In [25]:
arr=np.array([1,2,3,4,5],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
