In [6]:
import numpy as np
var=np.array([1,2,3,4,65,5,6,7,8,9,3])
vark= np.where(var/2==2)
print(vark)

(array([3], dtype=int64),)


In [8]:
var1=np.array([1,2,3,4,5,6])
x1=np.searchsorted(var1,9)
print(x1)

6


# Sort Function

In [11]:
var0=np.array([2,1,3,5,9,6,4,5,765,345,754,234,7,787,332,78,23,9,'asd','A'])
print(np.sort(var0))


['1' '2' '23' '234' '3' '332' '345' '4' '5' '5' '6' '7' '754' '765' '78'
 '787' '9' '9' 'A' 'asd']


In [14]:
varl=np.array([[1,9,3],[9,3,2],[99,23,1]])
print(np.sort(varl,axis=0 ))

[[ 1  3  1]
 [ 9  9  2]
 [99 23  3]]


# Filter

In [18]:
kar=np.array([2,1,3,5])
y= [True,False,True,False]
newa= kar[y]
print(newa)

[2 3]
