# Shape and reshape numpy

# shape

In [15]:
import numpy as np
var=np.array([[1,2,3,4,2],[1,2,3,4,5]])
print(var)
print()
print(var.shape)

[[1 2 3 4 2]
 [1 2 3 4 5]]

(2, 5)


In [22]:
var1=np.array([1,2,3,4,8,9,8],ndmin=8)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[[[[[1 2 3 4 8 9 8]]]]]]]]
8
(1, 1, 1, 1, 1, 1, 1, 7)


# reshape

In [56]:
v=np.array([1,2,3,4,1,2,3,4])
x=v.reshape(4,2,1,1)
print(x)

[[[[1]]

  [[2]]]


 [[[3]]

  [[4]]]


 [[[1]]

  [[2]]]


 [[[3]]

  [[4]]]]
